# Generated by Django 4.2.9 on 2024-03-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestsamp',
            new_name='timestamp',
        ),
    ]
