# Generated by Django 4.2.9 on 2024-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_timestsamp_orderupdate_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
